[package]
name = "bevy_sprite"
version = "0.1.0"
authors = ["Raiyan Hossain <ryanhossain9797@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.2"